### ISSUE TITLE
500 INTERNAL SERVER ERROR?

### ISSUE THREAD

**Issue by wdalhaj** [injoin/WP-Post-Attachments#11]
I use WP-Post-Attachment plugin. Really useful plugin, but recently it started to cause 500 internal server error when update/publish. The error disappeared when i deactivated the plugin. Any idea?

useful info : 
- Wordpress version : 3.5.1–en_US 
- Other [Activated] plugins : 
  Add Custom Fields to Media
  Admin Menu Editor
  BAW Post Views Count
  Contact Form 7
  Google sitemap plugin
  Members
  Official StatCounter Plugin
  Really Simple CAPTCHA
  Really simple Facebook Twitter share buttons
  Resize Image After Upload
  WP-RTL

**Comment by gustavohenke** [comment]
Hey @wdalhaj, 
Thanks for reporting the bug, I've not developed it for almostly 8 months now.

I'll see what can I do for you.

**Comment by wdalhaj** [comment]
Thanks @gustavohenke ! Now its 9 years instead of 8 months XD !
